### ISSUE TITLE
fake

### ISSUE THREAD

**Issue by orphanlol** [sladerbenk/Klockcraft-Bedrock#1]
klockcraft fake

**Comment by sladerbenk** [comment]
shut the fuck up you fucking nigger

**Comment by orphanlol** [comment]
![image](https://github.com/sladerbenk/Klockcraft-Bedrock/assets/83834491/a07dea67-bb4e-49fb-81c5-506c7662a749)

**Comment by stabbyfork** [comment]
-5000 social credit >:(

**Comment by sladerbenk** [comment]
You are stupid

**Comment by catfoolyou** [comment]
Why are you editing people's comments?
